### ISSUE TITLE
Round Lights pierce boxes

### ISSUE THREAD

**Issue by hjc2** [hjc2/rats#55]
you will get hit through boxes on round lights

**Comment by hjc2** [comment]
![image](https://github.com/user-attachments/assets/be3ebe8d-eaec-4cf7-b667-bc4068daa357)

stepping on this tile - you die

![image](https://github.com/user-attachments/assets/28480718-2481-4842-b8c0-6e4b75cf514e)

**Comment by leldridg** [comment]
The first solution I think of for this is using raycasting. It would be much like the kind used for flashlights / directional lights, but instead of casting a ray in a forward direction, you would be casting a ray of length r (light radius) out from the center of the point light every frame in the direction of the player. As in the case of the flashlights, if the ray hits a box first, it shouldn't detect or reset the player.
